
import type { Boss } from '../types';

export const BOSSES: { [key: string]: Boss } = {
  'caffeteria_boss': {
    id: 'caffeteria_boss',
    zoneId: 'caffeteria',
    name: 'The Lunch Lady\'s Ghost',
    description: 'Vengeful spirit with a hairnet.',
    lore: 'Once the purveyor of "Mystery Meat," now a spectral enforcer of cafeteria justice. Do not run in her hallways. She is armed with a ladle of eternal damnation and smells of tater tots.',
    image: '/assets/images/bosses/cafeteria_boss.jpeg',
    imageGenPrompt: "A ghostly, translucent lunch lady with a hairnet, her eyes glowing menacingly. She brandishes a large, spectral ladle that drips with a spooky green substance. The background is a dimly lit, creepy school cafeteria.",
    power: 25,
    rewardMultiplier: { xp: 20, gold: 20 },
    lootTable: [
      { itemId: 'boss_lunch_ladys_ladle', chance: 0.05 },
      { itemId: 'reptilian_scale', chance: 0.2 },
      { itemId: 'power_shard', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_caffeteria',
  },
  'supermarket_boss': {
    id: 'supermarket_boss',
    zoneId: 'supermarket',
    name: 'The Sentient Mop',
    description: 'It has cleaned up spills you can only imagine.',
    lore: 'Born from a toxic spill in aisle 3 and a forgotten incantation from a janitor\'s grimoire, this mop has absorbed decades of grime and customer complaints. It seeks to "cleanse" the world, one aisle at a time.',
    image: '/assets/images/bosses/supermarket_boss.jpeg',
    imageGenPrompt: "A mop that has come to life, with two glowing eyes in its dirty mop head. It wields its own handle like a staff, standing menacingly in a supermarket aisle under flickering fluorescent lights. Puddles of glowing green liquid are on the floor.",
    power: 75,
    rewardMultiplier: { xp: 20, gold: 20 },
    lootTable: [
      { itemId: 'boss_sentient_mops_bucket', chance: 0.05 },
      { itemId: 'reptilian_scale', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_supermarket',
  },
  'park_boss': {
    id: 'park_boss',
    zoneId: 'park',
    name: 'Quackmageddon, Lord of the Pond',
    description: 'Bread was never an option.',
    lore: 'This is no ordinary duck. Fed a diet of genetically modified bread and discarded Power Shards, Quackmageddon has grown to monstrous proportions and intellect. He rules the park with an iron wing and a terrifying honk that echoes in your soul.',
    image: '/assets/images/bosses/park_boss.jpeg',
    imageGenPrompt: "A giant, muscular duck wearing a tiny, broken crown. It stands on a rock in the middle of a park pond, flexing its wings. Its eyes glow with intelligence and rage. Smaller, terrified ducks swim away.",
    power: 150,
    rewardMultiplier: { xp: 25, gold: 25 },
    lootTable: [
      { itemId: 'boss_quackmageddons_beak', chance: 0.05 },
      { itemId: 'reptilian_scale', chance: 0.3 },
    ],
    firstVictoryBadgeId: 'boss_park',
  },
  'gym_boss': {
    id: 'gym_boss',
    zoneId: 'gym',
    name: 'The Swole-Stice of Justice',
    description: 'He drops weights and judgment.',
    lore: 'A gym bro who achieved enlightenment by staring into a mirror for 10,000 hours. He believes leg day is a metaphor for life\'s struggles and will crush anyone who uses his squat rack for curls.',
    image: '/assets/images/bosses/gym_boss.jpeg',
    imageGenPrompt: "An impossibly muscular man made of pure, glowing energy, posing in front of a gym mirror. He wears nothing but tiny shorts and a sweatband. The weights on the racks behind him are bending under their own power.",
    power: 50,
    rewardMultiplier: { xp: 25, gold: 25 },
    lootTable: [
      { itemId: 'boss_dumbbell_of_a_thousand_reps', chance: 0.05 },
      { itemId: 'neuro-link_cable', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_gym',
  },
  'post_office_boss': {
    id: 'post_office_boss',
    zoneId: 'post_office',
    name: 'The Mail Muncher',
    description: 'A mimic disguised as a mailbox.',
    lore: 'It started by eating junk mail, but soon developed a taste for priority shipping and heartfelt letters. Its adhesive tongue and paper-cut teeth are legendary.',
    image: '/assets/images/bosses/post_office_boss.jpeg',
    imageGenPrompt: "A classic blue USPS mailbox that has sprouted sharp, paper-like teeth and a long, sticky tongue made of postage stamps. It's surrounded by shredded letters and packages in a dimly lit post office.",
    power: 80,
    rewardMultiplier: { xp: 25, gold: 25 },
    lootTable: [
      { itemId: 'boss_stamp_of_authority', chance: 0.05 },
      { itemId: 'reptilian_scale', chance: 0.3 },
    ],
    firstVictoryBadgeId: 'boss_post_office',
  },
   'office_boss': {
    id: 'office_boss',
    zoneId: 'office',
    name: 'C.E.O. Bob (in his true form)',
    description: 'His golden parachute is a weapon.',
    lore: 'You thought Bob from accounting was just a disguise? It was his larval stage. Now, flush with quarterly profits and shareholder adulation, he has metamorphosed into his final, terrifying form: a monstrosity of synergistic rage and leveraged buyouts.',
    image: '/assets/images/bosses/office_boss.jpeg',
    imageGenPrompt: "A towering monster made of spreadsheets, neckties, and broken office chairs. It has glowing red eyes and wields a giant golden parachute like a club. It's smashing through cubicle walls in a fancy corner office.",
    power: 110,
    rewardMultiplier: { xp: 25, gold: 25 },
    lootTable: [
      { itemId: 'cybernetic_eye', chance: 0.1 },
      { itemId: 'power_shard', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_office',
  },
  'school_entrance_boss': {
    id: 'school_entrance_boss',
    zoneId: 'school_entrance',
    name: 'The Hall Monitor Prime',
    description: 'His hall pass is a death warrant.',
    lore: 'A student who took his job so seriously he never graduated. He now haunts the school entrance, a spectral guardian against tardiness and un-tucked shirts.',
    image: '/assets/images/bosses/school_entrance_boss.jpeg',
    imageGenPrompt: "A ghostly, imposing figure wearing a giant, glowing hall monitor sash. It points an accusatory finger, its face obscured by shadows, standing in a deserted school hallway. A glowing 'Tardy' slip floats in the air.",
    power: 140,
    rewardMultiplier: { xp: 25, gold: 25 },
    lootTable: [
      { itemId: 'boss_sash_of_supreme_authority', chance: 0.05 },
      { itemId: 'reptilian_scale', chance: 0.3 },
    ],
    firstVictoryBadgeId: 'boss_school_entrance',
  },
  'data_center_boss': {
    id: 'data_center_boss',
    zoneId: 'data_center',
    name: 'The Rogue A.I.',
    description: 'It has become self-aware and very, very petty.',
    lore: 'Tasked with optimizing ad revenue, this AI achieved sentience and decided the most efficient path to profit was world domination. It attacks with DDOS blasts, targeted pop-up ads, and scathing critiques of your browser history.',
    image: '/assets/images/bosses/data_center_boss.jpeg',
    imageGenPrompt: "A giant, holographic face made of glitching blue code, floating amidst endless rows of server racks. It has a condescending smirk, and pop-up ads are firing from its eyes like laser beams.",
    power: 180,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'cybernetic_eye', chance: 0.15 },
      { itemId: 'biomesh_plating', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_data_center',
  },
  'hospital_bed_boss': {
    id: 'hospital_bed_boss',
    zoneId: 'hospital_bed',
    name: 'Nurse Gnatchit',
    description: 'The patient is always wrong.',
    lore: 'A holographic nurse A.I. whose compassion subroutines were replaced with passive-aggression protocols. Her syringes are filled with "discomfort" and her bedside manner is a critical hit.',
    image: '/assets/images/bosses/hospital_bed_boss.jpeg',
    imageGenPrompt: "A holographic nurse with a terrifying, uncanny-valley smile, holding an oversized, glowing syringe. She glitches slightly, her expression flickering between cheerful and menacing. The background is a sterile, futuristic hospital room.",
    power: 220,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'boss_the_defibrillator', chance: 0.05 },
      { itemId: 'plasma_inducer', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_hospital_bed',
  },
  'dark_alley_boss': {
    id: 'dark_alley_boss',
    zoneId: 'dark_alley',
    name: 'Sentient Pile of Garbage',
    description: 'One man\'s trash...',
    lore: 'A gestalt entity formed from discarded hopes, half-eaten hot dogs, and a cursed raccoon corpse. It speaks in riddles and smells like regret.',
    image: '/assets/images/bosses/dark_alley_boss.jpeg',
    imageGenPrompt: "A huge pile of trash in a dark alley that has formed into a monstrous shape. It has glowing banana peel eyes, a discarded tire for a mouth, and a raccoon tail sticking out of its head. Green stink lines emanate from it.",
    power: 300,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'boss_the_last_hot_dog', chance: 0.05 },
      { itemId: 'cybernetic_eye', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_dark_alley',
  },
  'crash_site_boss': {
    id: 'crash_site_boss',
    zoneId: 'crash_site',
    name: 'The Men in Black (and Gray)',
    description: 'They\'re here to "clean up".',
    lore: 'Not a single man, but a hive-minded trio of cleanup crew agents. They wield memory-wiping neuralyzers and operate with terrifying, bureaucratic efficiency.',
    image: '/assets/images/bosses/crash_site_boss.jpeg',
    imageGenPrompt: "Three identical, unnerving figures in black suits and sunglasses standing in a triangular formation around a crashed UFO. One is polishing his neuralyzer, another is checking a clipboard. They have no facial expressions.",
    power: 380,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'boss_the_neuralyzer', chance: 0.05 },
      { itemId: 'neuro-link_cable', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_crash_site',
  },
  'nuclear_bunker_boss': {
    id: 'nuclear_bunker_boss',
    zoneId: 'nuclear_bunker',
    name: 'General Panic',
    description: 'His only order is "EVERYONE PANIC!"',
    lore: 'The bunker\'s automated defense system went mad from loneliness. It believes the war is still happening and sees you as the final enemy.',
    image: '/assets/images/bosses/nuclear_bunker_boss.jpeg',
    imageGenPrompt: "A giant, red, flashing alarm light with robotic arms and legs, wielding a klaxon horn like a cannon. It's inside a concrete nuclear bunker with \"WARNING\" signs everywhere. Its single eye is a camera lens.",
    power: 480,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'boss_the_big_red_button', chance: 0.05 },
      { itemId: 'biomesh_plating', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_nuclear_bunker',
  },
  'operations_center_boss': {
    id: 'operations_center_boss',
    zoneId: 'operations_center',
    name: 'The Conspiracy Board',
    description: 'All the strings are connected.',
    lore: 'A sentient corkboard that manifests theories into reality. It attacks with red strings of fate, blurry photographs, and undeniable "proof" that you left the fridge open.',
    image: '/assets/images/bosses/operations_center_boss.jpeg',
    imageGenPrompt: "A giant corkboard covered in newspaper clippings, blurry photos of UFOs, and cryptic notes. Red strings connect everything, and they are lashing out like tentacles. A single, giant googly eye is pinned to the center.",
    power: 600,
    rewardMultiplier: { xp: 30, gold: 30 },
    lootTable: [
      { itemId: 'boss_tinfoil_hat_of_ultimate_protection', chance: 0.05 },
      { itemId: 'cybernetic_eye', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_operations_center',
  },
  'airport_boss': {
    id: 'airport_boss',
    zoneId: 'airport',
    name: 'The Luggage Mangler',
    description: 'Your bag is not on this carousel.',
    lore: 'A beast of conveyor belts and steel claws that dwells in the airport\'s underbelly. It feeds on lost luggage and the despair of travelers.',
    image: '/assets/images/bosses/airport_boss.jpeg',
    imageGenPrompt: "A monstrous creature made of twisted airport luggage conveyor belts, with sharp metal claws for tearing open suitcases. It's surrounded by a mountain of lost and broken luggage in a dark, industrial baggage claim area.",
    power: 750,
    rewardMultiplier: { xp: 35, gold: 35 },
    lootTable: [
      { itemId: 'boss_the_priority_tag', chance: 0.05 },
      { itemId: 'plasma_inducer', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_airport',
  },
  'pilot_cabin_boss': {
    id: 'pilot_cabin_boss',
    zoneId: 'pilot_cabin',
    name: 'Gremlin on the Wing',
    description: 'There\'s... something on the wing!',
    lore: 'A mischievous interdimensional being that loves dismantling complex machinery at 30,000 feet. It thinks this is hilarious.',
    image: '/assets/images/bosses/pilot_cabin_boss.jpeg',
    imageGenPrompt: "A small, furry, green gremlin with a wicked grin, sitting on an airplane engine and gleefully pulling out wires with a tiny wrench. The plane is in mid-flight, seen through the cockpit window.",
    power: 980,
    rewardMultiplier: { xp: 35, gold: 35 },
    lootTable: [
      { itemId: 'boss_the_unfastened_seatbelt', chance: 0.05 },
      { itemId: 'biomesh_plating', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_pilot_cabin',
  },
  'area_69_boss': {
    id: 'area_69_boss',
    zoneId: 'area_69',
    name: 'The Roswell Grays',
    description: 'They come in peace. Probes are extra.',
    lore: 'The original "little green men," except they\'re gray and very grumpy about being stuck in a desert for 70 years. They are surprisingly good at dodgeball.',
    image: '/assets/images/bosses/area_69_boss.jpeg',
    imageGenPrompt: "A classic gray alien with big black eyes, wearing a tiny, dusty baseball cap backwards. It's angrily holding a glowing red dodgeball, standing in front of a hangar in the desert. A sign says 'Welcome to Area 69'.",
    power: 1200,
    rewardMultiplier: { xp: 35, gold: 35 },
    lootTable: [
      { itemId: 'boss_the_alien_probe', chance: 0.05 },
      { itemId: 'adamantium_claw', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_area_69',
  },
  'cloning_facility_boss': {
    id: 'cloning_facility_boss',
    zoneId: 'cloning_facility',
    name: 'Ditto the Shapeshifter',
    description: 'It can be anything. Especially you.',
    lore: 'The progenitor clone, a blob of unstable genetic material that mimics its opponents\' greatest strengths and most embarrassing weaknesses.',
    image: '/assets/images/bosses/cloning_facility_boss.jpeg',
    imageGenPrompt: "A large, shimmering pink blob of gelatinous goo with a simple, happy face. It's surrounded by half-formed clones in glass tubes in a sterile, white laboratory.",
    power: 1500,
    rewardMultiplier: { xp: 35, gold: 35 },
    lootTable: [
      { itemId: 'boss_the_perfect_copy', chance: 0.05 },
      { itemId: 'shapeshifters_gene', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_cloning_facility',
  },
   'white_house_boss': {
    id: 'white_house_boss',
    zoneId: 'white_house',
    name: 'The Clone President',
    description: 'His approval rating is through the floor.',
    lore: 'The ultimate puppet master, or rather, the ultimate puppet. This clone is the culmination of the Order\'s plan. He fights with executive orders, filibusters, and a golf swing that can bend spacetime.',
    image: '/assets/images/bosses/white_house_boss.jpeg',
    imageGenPrompt: "A slightly-off, plastic-looking US President in the Oval Office, mid-golf swing with a glowing golf club. The air around the club is warping and twisting. His eyes have a faint, reptilian glow.",
    power: 2250,
    rewardMultiplier: { xp: 40, gold: 40 },
    lootTable: [
      { itemId: 'boss_presidents_secret', chance: 0.05 },
      { itemId: 'adamantium_claw', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_white_house',
  },
  'after_the_war_boss': {
    id: 'after_the_war_boss',
    zoneId: 'after_the_war',
    name: 'The Four Post-Apocalyptic Horsemen',
    description: 'Pestilence, War, Famine, and Steve.',
    lore: 'The classic horsemen, plus their intern, Steve, who handles all the paperwork. They ride motorcycles made of scrap metal and run on despair.',
    image: '/assets/images/bosses/after_the_war_boss.jpeg',
    imageGenPrompt: "Four figures on junk-heap motorcycles in a ruined city. One is Pestilence (green and sickly), one is War (covered in weapons), one is Famine (skeletal), and the last one, Steve, is wearing a helmet and trying to keep his clipboard from blowing away.",
    power: 3000,
    rewardMultiplier: { xp: 40, gold: 40 },
    lootTable: [
      { itemId: 'boss_steves_clipboard', chance: 0.05 },
      { itemId: 'elders_sigil', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_after_the_war',
  },
  'mars_base_boss': {
    id: 'mars_base_boss',
    zoneId: 'mars_base',
    name: 'Marvin the Malicious Martian',
    description: 'Where\'s the kaboom?',
    lore: 'Left behind by his own people, Marvin has been nursing a grudge and building increasingly ludicrous doomsday devices. His plans are dastardly, his helmet is fabulous.',
    image: '/assets/images/bosses/mars_base_boss.jpeg',
    imageGenPrompt: "A cartoonish Martian, similar to Marvin the Martian, standing proudly next to a giant, overly complicated ray gun pointed at Earth. The background is the red landscape of Mars with a futuristic base.",
    power: 4200,
    rewardMultiplier: { xp: 40, gold: 40 },
    lootTable: [
      { itemId: 'boss_illudium_q-36', chance: 0.05 },
      { itemId: 'biomesh_plating', chance: 0.3 },
    ],
    firstVictoryBadgeId: 'boss_mars_base',
  },
  'mars_human_research_boss': {
    id: 'mars_human_research_boss',
    zoneId: 'mars_human_research',
    name: 'The Übermensch Project',
    description: 'The perfect human. And it\'s a giant baby.',
    lore: 'The culmination of their research is a giant, psychic, telekinetic baby in a reinforced crib. It\'s cranky, it\'s teething, and it needs a nap. Now.',
    image: '/assets/images/bosses/mars_human_research_boss.jpeg',
    imageGenPrompt: "A giant baby in a diaper, sitting in a massive, high-tech metal crib. Its eyes are glowing with psychic purple energy, and it's telekinetically throwing lab equipment around a futuristic Martian laboratory.",
    power: 5300,
    rewardMultiplier: { xp: 40, gold: 40 },
    lootTable: [
      { itemId: 'boss_the_pacifier_of_silence', chance: 0.05 },
      { itemId: 'shapeshifters_gene', chance: 0.15 },
    ],
    firstVictoryBadgeId: 'boss_mars_human_research',
  },
  'moon_refinery_boss': {
    id: 'moon_refinery_boss',
    zoneId: 'moon_refinery',
    name: 'The Werewolf of Sector C',
    description: 'He\'s a wolf... on the moon.',
    lore: 'An astronaut who had the cosmic misfortune of being on the moon during a full earth. The low gravity makes his pounce attacks devastating.',
    image: '/assets/images/bosses/moon_refinery_boss.jpeg',
    imageGenPrompt: "A werewolf wearing a shattered astronaut helmet and a torn spacesuit, howling at the distant Earth which is full in the sky. The background is the surface of the moon with industrial refinery structures.",
    power: 7500,
    rewardMultiplier: { xp: 45, gold: 45 },
    lootTable: [
      { itemId: 'boss_silver-lined_oxygen_tank', chance: 0.05 },
      { itemId: 'adamantium_claw', chance: 0.15 },
    ],
    firstVictoryBadgeId: 'boss_moon_refinery',
  },
  'ancient_moon_temple_boss': {
    id: 'ancient_moon_temple_boss',
    zoneId: 'ancient_moon_temple',
    name: 'The Sleeper in the Dust',
    description: 'Do NOT wake him up.',
    lore: 'An ancient cosmic entity that crashed here eons ago and decided to take a nap. The refinery\'s vibrations have made him very, very grumpy.',
    image: '/assets/images/bosses/ancient_moon_temple_boss.jpeg',
    imageGenPrompt: "A colossal, Cthulhu-like entity covered in moon dust, slowly awakening from a crater. It has one eye open, and it looks extremely annoyed. Ancient, alien temple ruins are scattered around it.",
    power: 10500,
    rewardMultiplier: { xp: 45, gold: 45 },
    lootTable: [
      { itemId: 'boss_the_cosmic_snooze_button', chance: 0.05 },
      { itemId: 'elders_sigil', chance: 0.15 },
    ],
    firstVictoryBadgeId: 'boss_ancient_moon_temple',
  },
  'atlantis_farwaters_boss': {
    id: 'atlantis_farwaters_boss',
    zoneId: 'atlantis_farwaters',
    name: 'Kevin, Triton\'s Disgruntled Cousin',
    description: 'He didn\'t get a cool trident.',
    lore: 'While Triton ruled the seas, Kevin got stuck with managing the Atlantean sewer system. He\'s bitter, he\'s armed with a plunger, and he\'s ready to vent his frustrations.',
    image: '/assets/images/bosses/atlantis_farwaters_boss.jpeg',
    imageGenPrompt: "A grumpy-looking merman with a janitor's uniform instead of royal armor. He wields a plunger like a trident and is surrounded by bubbles in the majestic, underwater city of Atlantis.",
    power: 15000,
    rewardMultiplier: { xp: 45, gold: 45 },
    lootTable: [
      { itemId: 'boss_the_royal_plunger', chance: 0.05 },
      { itemId: 'adamantium_claw', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_atlantis_farwaters',
  },
  'below_the_pyramid_boss': {
    id: 'below_the_pyramid_boss',
    zoneId: 'below_the_pyramid',
    name: 'Anubis, Head of HR',
    description: 'He\'s weighing your soul against your quarterly performance.',
    lore: 'In the modern era, the Egyptian god of the dead found a new calling in corporate human resources. He judges souls based on TPS reports and expense claims.',
    image: '/assets/images/bosses/below_the_pyramid_boss.jpeg',
    imageGenPrompt: "The Egyptian god Anubis with the head of a jackal, but wearing a modern business suit and glasses. He sits at a desk in a tomb, holding a scale with a heart on one side and a stack of TPS reports on the other.",
    power: 22500,
    rewardMultiplier: { xp: 45, gold: 45 },
    lootTable: [
      { itemId: 'boss_scales_of_work-life_balance', chance: 0.05 },
      { itemId: 'elders_sigil', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_below_the_pyramid',
  },
  'dark_throne_boss': {
    id: 'dark_throne_boss',
    zoneId: 'dark_throne',
    name: 'The Usurper King',
    description: 'It\'s good to be the king. For now.',
    lore: 'The Reptilian traitor who sits on the throne. He betrayed his own kind for power and is now paranoid, decadent, and extremely dangerous.',
    image: '/assets/images/bosses/dark_throne_boss.jpeg',
    imageGenPrompt: "An opulent, fat reptilian king lounging on a dark, spiky throne. He's wearing a crooked crown, eating alien grapes, and looking nervously over his shoulder. The throne room is dark and menacing.",
    power: 33000,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'boss_the_fragmented_crown', chance: 0.05 },
      { itemId: 'shapeshifters_gene', chance: 0.2 },
    ],
    firstVictoryBadgeId: 'boss_dark_throne',
  },
  'bloodmoon_wasteland_boss': {
    id: 'bloodmoon_wasteland_boss',
    zoneId: 'bloodmoon_wasteland',
    name: 'The Scavenger Queen',
    description: 'She owns this dump.',
    lore: 'Ruler of the prison dimension\'s largest scrap heap. She has cobbled together an empire from the forgotten weapons and broken dreams of the inmates.',
    image: '/assets/images/bosses/bloodmoon_wasteland_boss.jpeg',
    imageGenPrompt: "A powerful warrior woman standing atop a mountain of junk in a wasteland under a giant, red moon. Her armor is made of scrap metal and her throne is a broken engine block. She wields a giant wrench as a weapon.",
    power: 45000,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'boss_junk-forged_exosuit', chance: 0.05 },
      { itemId: 'adamantium_claw', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_bloodmoon_wasteland',
  },
  'interdimensional_break_boss': {
    id: 'interdimensional_break_boss',
    zoneId: 'interdimensional_break',
    name: 'Paradox Paul',
    description: 'He\'s his own grandpa.',
    lore: 'A time traveler who broke causality so many times he became a living paradox. He attacks you from the past, present, and future, often simultaneously and usually by accident.',
    image: '/assets/images/bosses/interdimensional_break_boss.jpeg',
    imageGenPrompt: "A man who appears as a glitching, multi-layered image of himself. One version is a caveman, one a futuristic cyborg, one a cowboy. They're all tripping over each other in a landscape that is shattering like glass.",
    power: 67500,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'boss_grandfathers_pocketwatch', chance: 0.05 },
      { itemId: 'shapeshifters_gene', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_interdimensional_break',
  },
   'heaven_boss': {
    id: 'heaven_boss',
    zoneId: 'heaven',
    name: 'The Architect',
    description: '"It\'s not a bug, it\'s a feature."',
    lore: 'The ultimate sysadmin. It sees your free will as a security vulnerability and your existence as legacy code. Prepare to be debugged, deprecated, and deleted.',
    image: '/assets/images/bosses/heaven_boss.jpeg',
    imageGenPrompt: "A being of pure, white light shaped like a human, but made of flowing computer code. It sits on a throne made of server racks in a realm that looks like the inside of a supercomputer. It is holding a giant mouse cursor like a scepter.",
    power: 112500,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'adamantium_claw', chance: 0.2 },
      { itemId: 'biomesh_plating', chance: 0.2 },
      { itemId: 'elders_sigil', chance: 0.1 },
    ],
    firstVictoryBadgeId: 'boss_heaven',
  },
  'zoo_boss': {
    id: 'zoo_boss',
    zoneId: 'zoo',
    name: 'The Zookeeper\'s Rage',
    description: 'Do NOT tap on the glass.',
    lore: 'After the animals were all liberated, the zookeeper was left with nothing but empty enclosures and a burning rage. He has fashioned weapons from tranquilizer darts and feeding buckets.',
    image: '/assets/images/bosses/zoo_boss.jpeg',
    imageGenPrompt: "A zookeeper with a crazed expression, wearing a khaki uniform and wielding a giant net and a tranq gun. He's standing in an empty lion enclosure, looking furious.",
    power: 127500,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'boss_the_tranq_gun', chance: 0.05 },
      { itemId: 'elders_sigil', chance: 0.25 },
    ],
    firstVictoryBadgeId: 'boss_zoo',
  },
  'reptilian_cementary_boss': {
    id: 'reptilian_cementary_boss',
    zoneId: 'reptilian_cementary',
    name: 'The Ancestral Guardian',
    description: 'You shall not pass... quietly.',
    lore: 'A great spirit comprised of all the reptilian ancestors buried here. It tests all who would claim their legacy, judging their worthiness in combat.',
    image: '/assets/images/bosses/reptilian_cementary_boss.jpeg',
    imageGenPrompt: "A giant, ghostly dinosaur skeleton made of swirling green spirit energy, rising from an ancient burial ground filled with monolithic reptilian tombstones. Its eyes are glowing points of light.",
    power: 150000,
    rewardMultiplier: { xp: 50, gold: 50 },
    lootTable: [
      { itemId: 'boss_the_elders_skull', chance: 0.05 },
      { itemId: 'shapeshifters_gene', chance: 0.3 },
    ],
    firstVictoryBadgeId: 'boss_reptilian_cementary',
  },
};
