
export const imagePrompts = {
    // boss items
    "ladle.jpeg": "A large, spectral, glowing metal ladle, dripping with a mysterious green substance.",
    "soulDumbbell.jpeg": "A massive, black iron dumbbell that radiates a powerful aura of pure energy.",
    "stampOfAuthority.jpeg": "An ornate, heavy-duty rubber stamp with a glowing, otherworldly sigil on it, worn as a ring.",
    "hallMonitorSash.jpeg": "A bright orange hall monitor sash that glows with immense power.",
    "defibrillator.jpeg": "A pair of defibrillator paddles crackling with powerful lightning.",
    "lastHotDog.jpeg": "A petrified hot dog in a bun, hanging from a golden chain like a precious amulet.",
    "neuralyzer.jpeg": "A sleek, silver, pen-like device from Men In Black, emitting a bright flash.",
    "bigRedButton.jpeg": "A comically large, tempting red button mounted on a ring.",
    "tinfoilHat.jpeg": "An expertly crafted, shiny tinfoil hat that hums with protective energy.",
    "priorityTag.jpeg": "A glowing red \"PRIORITY\" luggage tag worn as a necklace.",
    "seatbeltFlail.jpeg": "A car seatbelt with a heavy metal buckle, being swung like a flail.",
    "alienProbe.jpeg": "A stereotypical alien anal probe device, glowing ominously.",
    "perfectCopy.jpeg": "A magical glowing exam paper with an A++ grade on it.",
    "goldenBeak.jpeg": "A powerful, golden duck beak worn as a helmet.",
    "mopBucket.jpeg": "A metal mop bucket worn as a helmet, with a single, knowing eye peering from inside.",
    "presidentsTie.jpeg": "A patriotic red, white, and blue tie, tied into a perfect knot and worn as a necklace.",
    "stevesClipboard.jpeg": "A powerful, glowing clipboard that radiates an aura of pure authority and paperwork.",
    "spaceModulator.jpeg": "The Illudium Q-36 Explosive Space Modulator from Looney Tunes.",
    "pacifierOfSilence.jpeg": "A large, ornate baby pacifier hanging from a chain, glowing with quieting energy.",
    "silverOxygenTank.jpeg": "An astronaut's oxygen tank backpack made of shining, polished silver.",
    "cosmicSnoozeButton.jpeg": "A ring with a large, glowing button shaped like a crescent moon and stars.",
    "royalPlunger.jpeg": "A golden toilet plunger, topped with a crown, held like a scepter.",
    "scalesOfWorkLife.jpeg": "A set of glowing, ethereal balancing scales.",
    "fragmentedCrown.jpeg": "A shattered royal crown, with the pieces floating together, held by a dark energy.",
    "junkExosuit.jpeg": "A powerful exosuit cobbled together from scrap metal, car parts, and old appliances.",
    "grandfathersWatch.jpeg": "An antique, ornate pocketwatch that seems to bend time around it.",
    "tranqGun.jpeg": "A high-tech tranquilizer dart gun, looking powerful and dangerous.",
    "eldersSkull.jpeg": "A giant, ancient, reptilian skull that glows with inner wisdom and power.",

    // bosses
    "cafeteria_boss.jpeg": "A ghostly, translucent lunch lady with a hairnet, her eyes glowing menacingly. She brandishes a large, spectral ladle that drips with a spooky green substance. The background is a dimly lit, creepy school cafeteria.",
    "supermarket_boss.jpeg": "A mop that has come to life, with two glowing eyes in its dirty mop head. It wields its own handle like a staff, standing menacingly in a supermarket aisle under flickering fluorescent lights. Puddles of glowing green liquid are on the floor.",
    "park_boss.jpeg": "A giant, muscular duck wearing a tiny, broken crown. It stands on a rock in the middle of a park pond, flexing its wings. Its eyes glow with intelligence and rage. Smaller, terrified ducks swim away.",
    "gym_boss.jpeg": "An impossibly muscular man made of pure, glowing energy, posing in front of a gym mirror. He wears nothing but tiny shorts and a sweatband. The weights on the racks behind him are bending under their own power.",
    "post_office_boss.jpeg": "A classic blue USPS mailbox that has sprouted sharp, paper-like teeth and a long, sticky tongue made of postage stamps. It's surrounded by shredded letters and packages in a dimly lit post office.",
    "office_boss.jpeg": "A towering monster made of spreadsheets, neckties, and broken office chairs. It has glowing red eyes and wields a giant golden parachute like a club. It's smashing through cubicle walls in a fancy corner office.",
    "school_entrance_boss.jpeg": "A ghostly, imposing figure wearing a giant, glowing hall monitor sash. It points an accusatory finger, its face obscured by shadows, standing in a deserted school hallway. A glowing 'Tardy' slip floats in the air.",
    "data_center_boss.jpeg": "A giant, holographic face made of glitching blue code, floating amidst endless rows of server racks. It has a condescending smirk, and pop-up ads are firing from its eyes like laser beams.",
    "hospital_bed_boss.jpeg": "A holographic nurse with a terrifying, uncanny-valley smile, holding an oversized, glowing syringe. She glitches slightly, her expression flickering between cheerful and menacing. The background is a sterile, futuristic hospital room.",
    "dark_alley_boss.jpeg": "A huge pile of trash in a dark alley that has formed into a monstrous shape. It has glowing banana peel eyes, a discarded tire for a mouth, and a raccoon tail sticking out of its head. Green stink lines emanate from it.",
    "crash_site_boss.jpeg": "Three identical, unnerving figures in black suits and sunglasses standing in a triangular formation around a crashed UFO. One is polishing his neuralyzer, another is checking a clipboard. They have no facial expressions.",
    "nuclear_bunker_boss.jpeg": "A giant, red, flashing alarm light with robotic arms and legs, wielding a klaxon horn like a cannon. It's inside a concrete nuclear bunker with \"WARNING\" signs everywhere. Its single eye is a camera lens.",
    "operations_center_boss.jpeg": "A giant corkboard covered in newspaper clippings, blurry photos of UFOs, and cryptic notes. Red strings connect everything, and they are lashing out like tentacles. A single, giant googly eye is pinned to the center.",
    "airport_boss.jpeg": "A monstrous creature made of twisted airport luggage conveyor belts, with sharp metal claws for tearing open suitcases. It's surrounded by a mountain of lost and broken luggage in a dark, industrial baggage claim area.",
    "pilot_cabin_boss.jpeg": "A small, furry, green gremlin with a wicked grin, sitting on an airplane engine and gleefully pulling out wires with a tiny wrench. The plane is in mid-flight, seen through the cockpit window.",
    "area_69_boss.jpeg": "A classic gray alien with big black eyes, wearing a tiny, dusty baseball cap backwards. It's angrily holding a glowing red dodgeball, standing in front of a hangar in the desert. A sign says 'Welcome to Area 69'.",
    "cloning_facility_boss.jpeg": "A large, shimmering pink blob of gelatinous goo with a simple, happy face. It's surrounded by half-formed clones in glass tubes in a sterile, white laboratory.",
    "white_house_boss.jpeg": "A slightly-off, plastic-looking US President in the Oval Office, mid-golf swing with a glowing golf club. The air around the club is warping and twisting. His eyes have a faint, reptilian glow.",
    "after_the_war_boss.jpeg": "Four figures on junk-heap motorcycles in a ruined city. One is Pestilence (green and sickly), one is War (covered in weapons), one is Famine (skeletal), and the last one, Steve, is wearing a helmet and trying to keep his clipboard from blowing away.",
    "mars_base_boss.jpeg": "A cartoonish Martian, similar to Marvin the Martian, standing proudly next to a giant, overly complicated ray gun pointed at Earth. The background is the red landscape of Mars with a futuristic base.",
    "mars_human_research_boss.jpeg": "A giant baby in a diaper, sitting in a massive, high-tech metal crib. Its eyes are glowing with psychic purple energy, and it's telekinetically throwing lab equipment around a futuristic Martian laboratory.",
    "moon_refinery_boss.jpeg": "A werewolf wearing a shattered astronaut helmet and a torn spacesuit, howling at the distant Earth which is full in the sky. The background is the surface of the moon with industrial refinery structures.",
    "ancient_moon_temple_boss.jpeg": "A colossal, Cthulhu-like entity covered in moon dust, slowly awakening from a crater. It has one eye open, and it looks extremely annoyed. Ancient, alien temple ruins are scattered around it.",
    "atlantis_farwaters_boss.jpeg": "A grumpy-looking merman with a janitor's uniform instead of royal armor. He wields a plunger like a trident and is surrounded by bubbles in the majestic, underwater city of Atlantis.",
    "below_the_pyramid_boss.jpeg": "The Egyptian god Anubis with the head of a jackal, but wearing a modern business suit and glasses. He sits at a desk in a tomb, holding a scale with a heart on one side and a stack of TPS reports on the other.",
    "dark_throne_boss.jpeg": "An opulent, fat reptilian king lounging on a dark, spiky throne. He's wearing a crooked crown, eating alien grapes, and looking nervously over his shoulder. The throne room is dark and menacing.",
    "bloodmoon_wasteland_boss.jpeg": "A powerful warrior woman standing atop a mountain of junk in a wasteland under a giant, red moon. Her armor is made of scrap metal and her throne is a broken engine block. She wields a giant wrench as a weapon.",
    "interdimensional_break_boss.jpeg": "A man who appears as a glitching, multi-layered image of himself. One version is a caveman, one a futuristic cyborg, one a cowboy. They're all tripping over each other in a landscape that is shattering like glass.",
    "heaven_boss.jpeg": "A being of pure, white light shaped like a human, but made of flowing computer code. It sits on a throne made of server racks in a realm that looks like the inside of a supercomputer. It is holding a giant mouse cursor like a scepter.",
    "zoo_boss.jpeg": "A zookeeper with a crazed expression, wearing a khaki uniform and wielding a giant net and a tranq gun. He's standing in an empty lion enclosure, looking furious.",
    "reptilian_cementary_boss.jpeg": "A giant, ghostly dinosaur skeleton made of swirling green spirit energy, rising from an ancient burial ground filled with monolithic reptilian tombstones. Its eyes are glowing points of light."
};
