export const imagePrompts = {
    // boss items
    "ladle.jpeg": "A large, spectral, glowing metal ladle, dripping with a mysterious green substance.",
    "soulDumbbell.jpeg": "A massive, black iron dumbbell that radiates a powerful aura of pure energy.",
    "stampOfAuthority.jpeg": "An ornate, heavy-duty rubber stamp with a glowing, otherworldly sigil on it, worn as a ring.",
    "hallMonitorSash.jpeg": "A bright orange hall monitor sash that glows with immense power.",
    "defibrillator.jpeg": "A pair of defibrillator paddles crackling with powerful lightning.",
    "lastHotDog.jpeg": "A petrified hot dog in a bun, hanging from a golden chain like a precious amulet.",
    "neuralyzer.jpeg": "A sleek, silver, pen-like device from Men In Black, emitting a bright flash.",
    "bigRedButton.jpeg": "A comically large, tempting red button mounted on a ring.",
    "tinfoilHat.jpeg": "An expertly crafted, shiny tinfoil hat that hums with protective energy.",
    "priorityTag.jpeg": "A glowing red \"PRIORITY\" luggage tag worn as a necklace.",
    "seatbeltFlail.jpeg": "A car seatbelt with a heavy metal buckle, being swung like a flail.",
    "alienProbe.jpeg": "A stereotypical alien anal probe device, glowing ominously.",
    "perfectCopy.jpeg": "A magical glowing exam paper with an A++ grade on it.",
    "goldenBeak.jpeg": "A powerful, golden duck beak worn as a helmet.",
    "mopBucket.jpeg": "A metal mop bucket worn as a helmet, with a single, knowing eye peering from inside.",
    "presidentsTie.jpeg": "A patriotic red, white, and blue tie, tied into a perfect knot and worn as a necklace.",
    "stevesClipboard.jpeg": "A powerful, glowing clipboard that radiates an aura of pure authority and paperwork.",
    "spaceModulator.jpeg": "The Illudium Q-36 Explosive Space Modulator from Looney Tunes.",
    "pacifierOfSilence.jpeg": "A large, ornate baby pacifier hanging from a chain, glowing with quieting energy.",
    "silverOxygenTank.jpeg": "An astronaut's oxygen tank backpack made of shining, polished silver.",
    "cosmicSnoozeButton.jpeg": "A ring with a large, glowing button shaped like a crescent moon and stars.",
    "royalPlunger.jpeg": "A golden toilet plunger, topped with a crown, held like a scepter.",
    "scalesOfWorkLife.jpeg": "A set of glowing, ethereal balancing scales.",
    "fragmentedCrown.jpeg": "A shattered royal crown, with the pieces floating together, held by a dark energy.",
    "junkExosuit.jpeg": "A powerful exosuit cobbled together from scrap metal, car parts, and old appliances.",
    "grandfathersWatch.jpeg": "An antique, ornate pocketwatch that seems to bend time around it.",
    "tranqGun.jpeg": "A high-tech tranquilizer dart gun, looking powerful and dangerous.",
    "eldersSkull.jpeg": "A giant, ancient, reptilian skull that glows with inner wisdom and power.",
    // zone items
    };
