import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const supermarketItems: { [key: string]: Item } = {
  'supermarket_price_gun': { id: 'supermarket_price_gun', name: 'Price Gun', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 8,
    description: 'Fires adhesive labels of economic despair. Effective at blinding and confusing foes.',
    icon: '🔫',
    image: 'images/attributes/weapon/priceGun.jpeg',
    imageGenPrompt: 'A red plastic price sticker gun, looking menacing.',
    forgeAttributes: { '5': 'power_t1', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'supermarket_vest': { id: 'supermarket_vest', name: 'Employee Vest', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 7,
    description: 'This garish blue vest makes you look like you belong, granting you access to employee-only areas.',
    icon: ' V ',
    image: 'images/attributes/armor/employeeVest.jpeg',
    imageGenPrompt: 'A cheap, bright blue supermarket employee vest with a name tag that says "Agent".',
    forgeAttributes: { '5': 'power_t1', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'supermarket_wheel': { id: 'supermarket_wheel', name: 'Wobbly Cart Wheel', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 4,
    description: 'The legendary fourth wheel of a shopping cart, cursed to never roll straight. Its chaotic energy is palpable.',
    icon: '☸️',
    image: 'images/attributes/misc/cartWheel.jpeg',
    imageGenPrompt: 'A single, broken shopping cart wheel, emitting a faint, chaotic aura.',
    forgeAttributes: { '5': 'gold_t1', '10': 'loot_t1', '15': 'perm_perk_misc' } },
  'supermarket_coupon': { id: 'supermarket_coupon', name: 'Expired Coupon', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 2,
    description: 'It\'s for 10% off a brand of cereal that hasn\'t been sold in 20 years. Still, it feels important.',
    icon: ' C ',
    image: 'images/attributes/misc/expiredCoupon.jpeg',
    imageGenPrompt: 'A yellowed, expired coupon for a forgotten brand of cereal.',
    forgeAttributes: { '5': 'gold_t1', '10': 'loot_t1', '15': 'perm_perk_misc' } },
  'supermarket_loyalty_card': { id: 'supermarket_loyalty_card', name: 'Loyalty Card', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 5,
    description: 'Tracks your every purchase in exchange for a 1% discount. A fair trade.',
    icon: ' L ',
    image: 'images/attributes/ring/loyaltyCard.jpeg',
    imageGenPrompt: 'A plastic supermarket loyalty card with a hole punched in it, worn on a finger.',
    forgeAttributes: { '5': 'power_t1', '10': 'loot_t1', '15': 'perm_perk_ring' } },
};
