import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const parkItems: { [key: string]: Item } = {
  'park_frisbee': { id: 'park_frisbee', name: 'Discarded Frisbee', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 10,
    description: 'Still sharp enough to be a formidable throwing weapon. Captain America would be proud.',
    icon: '🛸',
    image: 'images/zone-items/frisbee.png',
    imageGenPrompt: 'A chipped, red plastic frisbee used as a chakram-style weapon.',
    forgeAttributes: { '5': 'power_t1', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'park_bench_plank': { id: 'park_bench_plank', name: 'Bench Plank', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 9,
    description: 'A sturdy piece of wood from a park bench. Can be worn as a chestplate in a pinch.',
    icon: ' B ',
    image: 'images/zone-items/benchPlank.png',
    imageGenPrompt: 'A weathered wooden plank from a park bench, strapped to a person as crude armor.',
    forgeAttributes: { '5': 'power_t1', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'park_duck_feather': { id: 'park_duck_feather', name: 'Duck Feather Amulet', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 6,
    description: 'The ducks in this park are not normal. This feather seems to whisper warnings.',
    icon: '🪶',
    image: 'images/zone-items/duckFeatherAmulet.png',
    imageGenPrompt: 'A single, iridescent duck feather tied to a leather cord as a necklace.',
    forgeAttributes: { '5': 'gold_t1', '10': 'xp_t1', '15': 'perm_perk_amulet' } },
  'park_squirrel_nut': { id: 'park_squirrel_nut', name: 'Squirrel\'s Acorn', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 3,
    description: 'This acorn was clearly very important to a very angry squirrel. It feels... powerful.',
    icon: '🌰',
    image: 'images/zone-items/squirrelAcorn.png',
    imageGenPrompt: 'A single, unusually large and shiny acorn.',
    forgeAttributes: { '5': 'gold_t1', '10': 'loot_t1', '15': 'perm_perk_misc' } },
  'park_goose_blade': { id: 'park_goose_blade', name: 'Goose Blade', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 25,
    description: 'A weapon forged in pure, unadulterated goose rage. It honks when swung.',
    icon: ' G ',
    image: 'images/zone-items/gooseBlade.png',
    imageGenPrompt: 'A shortsword with a handle shaped like a goose head and a blade like a giant feather.',
    forgeAttributes: { '5': 'power_t3', '10': 'xp_t2', '15': 'perm_perk_weapon' } },
};
