import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const officeItems: { [key: string]: Item } = {
  'office_keyboard': { id: 'office_keyboard', name: 'Wireless Keyboard', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 18, description: 'The pen is mightier than the sword, but this is heavier.', icon: '⌨️', image: 'images/zone-items/keyboard.png', imageGenPrompt: 'A heavy, old-school mechanical keyboard being swung like a club.', forgeAttributes: { '5': 'power_t1', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'office_suit_jacket': { id: 'office_suit_jacket', name: 'Ill-fitting Suit Jacket', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 17, description: 'Smells of cheap cologne and desperation. Blends right in.', icon: '🧥', image: 'images/zone-items/suitJacket.png', imageGenPrompt: 'A generic, grey, ill-fitting business suit jacket.', forgeAttributes: { '5': 'power_t1', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'office_stapler': { id: 'office_stapler', name: 'Red Swingline Stapler', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 13, description: 'An object of obsession. Its power is inexplicable.', icon: ' S ', image: 'images/zone-items/redStapler.png', imageGenPrompt: 'A bright red Swingline stapler, glowing with an internal fire.', forgeAttributes: { '5': 'power_t1', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'office_badge': { id: 'office_badge', name: 'Security Badge', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 12, description: 'Opens doors that should remain closed.', icon: '💳', image: 'images/zone-items/securityBadge.png', imageGenPrompt: 'A keycard with a hologram of an eye, hanging from a lanyard.', forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
  'office_locket': { id: 'office_locket', name: 'Locket of Secrets', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 14, description: 'Whispers truths to its wearer.', icon: '📿', image: 'images/zone-items/locketOfSecrets.png', imageGenPrompt: 'An ornate silver locket that seems to glow from within.', forgeAttributes: { '5': 'gold_t2', '10': 'xp_t2', '15': 'perm_perk_amulet' } },
};
