import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const nuclearBunkerItems: { [key: string]: Item } = {
  'bunker_lead_pipe': { id: 'bunker_lead_pipe', name: 'Lead Pipe', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 75, description: 'For solving mysteries and cracking skulls.', icon: '🔧', image: 'images/attributes/weapon/leadPipe.jpeg', imageGenPrompt: 'A heavy, dented lead pipe.', forgeAttributes: { '5': 'power_t3', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'bunker_hazmat_suit': { id: 'bunker_hazmat_suit', name: 'Hazmat Suit', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 70, description: 'Protects from radiation, but not from blunt force trauma.', icon: '👨‍🚀', image: 'images/attributes/armor/hazmatSuit.jpeg', imageGenPrompt: 'A bright yellow, full-body hazmat suit.', forgeAttributes: { '5': 'power_t3', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'bunker_geiger_counter': { id: 'bunker_geiger_counter', name: 'Geiger Counter Ring', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 60, description: 'Clicks faster when interesting things are near.', icon: ' G ', image: 'images/attributes/ring/geigerCounter.jpeg', imageGenPrompt: 'A ring with a small, functioning Geiger counter on it that clicks ominously.', forgeAttributes: { '5': 'power_t3', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'bunker_launch_key': { id: 'bunker_launch_key', name: 'Launch Key', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 65, description: 'Two are required to turn, but one is enough to cause trouble.', icon: '🔑', image: 'images/attributes/misc/launchKey.jpeg', imageGenPrompt: 'A military-style key with a large red tag, worn on a chain.', forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
};
