import type { Item } from "../../../types";
import {
  ItemRarity,
  ItemType,
  EquipmentSlot,
  ItemCategory,
} from "../../../types";

export const marsHumanResearchItems: { [key: string]: Item } = {
  mars_research_gene_gun: {
    id: "mars_research_gene_gun",
    name: "Gene-Splicer Gun",
    rarity: ItemRarity.Epic,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Weapon,
    power: 750,
    description: "Rewrites enemy DNA into something more... manageable.",
    icon: "🧬",
    forgeAttributes: {
      "5": "power_t6",
      "10": "xp_t2",
      "15": "perm_perk_weapon",
    },
  },
  mars_research_biohazard_suit: {
    id: "mars_research_biohazard_suit",
    name: "Biohazard Suit",
    rarity: ItemRarity.Epic,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Armor,
    power: 720,
    description: "For when the experiments get loose.",
    icon: "☣️",
    forgeAttributes: {
      "5": "power_t6",
      "10": "gold_t2",
      "15": "perm_perk_armor",
    },
  },
  mars_research_sentient_growth: {
    id: "mars_research_sentient_growth",
    name: "Sentient Growth",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Misc,
    power: 680,
    description: "It whispers the secrets of genetics.",
    icon: "🌱",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  mars_research_syringe: {
    id: "mars_research_syringe",
    name: "Syringe",
    rarity: ItemRarity.Common,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Weapon,
    power: 690,
    description: "Filled with an unknown, glowing substance.",
    icon: "💉",
    image: "images/zone-items/syringe.png",
    imageGenPrompt: "A medical syringe filled with a glowing blue liquid.",
    forgeAttributes: {
      "5": "power_t6",
      "10": "xp_t1",
      "15": "perm_perk_weapon",
    },
  },
  mars_research_lab_notes: {
    id: "mars_research_lab_notes",
    name: "Lab Notes",
    rarity: ItemRarity.Rare,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Misc,
    power: 650,
    description: 'Frantic scribbles about "Project Chimera".',
    icon: " N ",
    image: "images/zone-items/labNotes.png",
    imageGenPrompt:
      "A clipboard with sheets of paper covered in frantic, scientific handwriting.",
    forgeAttributes: {
      "5": "gold_t1",
      "10": "loot_t1",
      "15": "perm_perk_misc",
    },
  },
  mars_research_prototype_implant: {
    id: "mars_research_prototype_implant",
    name: "Prototype Implant",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Standard,
    slot: EquipmentSlot.Ring,
    power: 700,
    description: "A neural implant that hums with forbidden knowledge.",
    icon: " I ",
    image: "images/zone-items/prototypeImplant.png",
    imageGenPrompt: "A small, complex microchip that can be worn as a ring.",
    forgeAttributes: {
      "5": "power_t6",
      "10": "loot_t3",
      "15": "perm_perk_ring",
    },
  },
};
