import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const atlantisFarwatersItems: { [key: string]: Item } = {
  'atlantis_trident': { id: 'atlantis_trident', name: 'Atlantean Trident', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 2500, description: 'Commands the respect of the seven seas.', icon: '🔱', forgeAttributes: { '5': 'power_t8', '10': 'xp_t3', '15': 'perm_perk_weapon' } },
  'atlantis_coral_armor': { id: 'atlantis_coral_armor', name: 'Coral Armor', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 2400, description: 'Grown, not forged.', icon: '🌊', forgeAttributes: { '5': 'power_t7', '10': 'gold_t3', '15': 'perm_perk_armor' } },
  'atlantis_pearl_of_wisdom': { id: 'atlantis_pearl_of_wisdom', name: 'Pearl of Wisdom', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 2200, description: 'Whispers the secrets of the deep.', icon: '⚪', forgeAttributes: { '5': 'gold_t3', '10': 'loot_t3', '15': 'perm_perk_misc' } },
  'atlantis_barnacle_club': { id: 'atlantis_barnacle_club', name: 'Barnacle Club', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 2100,
    description: 'A piece of driftwood covered in angry barnacles.',
    icon: ' B ',
    image: 'images/attributes/weapon/barnacleClub.jpeg',
    imageGenPrompt: 'A heavy piece of driftwood covered in sharp barnacles, used as a club.',
    forgeAttributes: { '5': 'power_t7', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'atlantis_seaweed_garb': { id: 'atlantis_seaweed_garb', name: 'Seaweed Garb', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 2000,
    description: 'Surprisingly resilient and smells of low tide.',
    icon: ' S ',
    image: 'images/attributes/armor/seaweedGarb.jpeg',
    imageGenPrompt: 'Armor woven from thick, durable seaweed.',
    forgeAttributes: { '5': 'power_t7', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'atlantis_conch_horn': { id: 'atlantis_conch_horn', name: 'Conch Horn', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 2150,
    description: 'Sounds the call to battle, or to dinner.',
    icon: '🐚',
    image: 'images/attributes/misc/conchHorn.jpeg',
    imageGenPrompt: 'A large, ornate conch shell that can be used as a horn.',
    forgeAttributes: { '5': 'gold_t1', '10': 'loot_t1', '15': 'perm_perk_misc' } },
  'atlantis_abyssal_gem': { id: 'atlantis_abyssal_gem', name: 'Abyssal Gem', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 2300,
    description: 'A gemstone that absorbs light and hope.',
    icon: ' A ',
    image: 'images/attributes/ring/abyssalGem.jpeg',
    imageGenPrompt: 'A ring set with a gemstone as dark as the deep ocean, absorbing all light.',
    forgeAttributes: { '5': 'power_t7', '10': 'loot_t2', '15': 'perm_perk_ring' } },
  'atlantis_kraken_ink': { id: 'atlantis_kraken_ink', name: 'Kraken Ink', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 2350,
    description: 'A vial of ink from a leviathan. It writes stories of forgotten ages.',
    icon: ' K ',
    image: 'images/attributes/amulet/krakenInk.jpeg',
    imageGenPrompt: 'A small vial filled with swirling, dark kraken ink, worn as an amulet.',
    forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
};
