import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const bloodmoonWastelandItems: { [key: string]: Item } = {
  'bloodmoon_chainsaw_sword': { id: 'bloodmoon_chainsaw_sword', name: 'Chainsaw Sword', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 8500, description: 'Subtlety is overrated.', icon: '⛓️', forgeAttributes: { '5': 'power_t8', '10': 'xp_t3', '15': 'perm_perk_weapon' } },
  'bloodmoon_scrapmetal_pauldrons': { id: 'bloodmoon_scrapmetal_pauldrons', name: 'Scrapmetal Pauldrons', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 8200, description: 'Fashioned from the husks of war machines.', icon: '🤖', forgeAttributes: { '5': 'power_t8', '10': 'gold_t3', '15': 'perm_perk_armor' } },
  'bloodmoon_mutagen_vial': { id: 'bloodmoon_mutagen_vial', name: 'Mutagen Vial', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 7800, description: 'Unleash your inner beast.', icon: '🧪', forgeAttributes: { '5': 'power_t8', '10': 'loot_t3', '15': 'perm_perk_ring' } },
  'bloodmoon_shiv': { id: 'bloodmoon_shiv', name: 'Shiv', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 7700,
    description: 'A sharpened piece of scrap metal. Prison rules apply.',
    icon: ' S ',
    image: 'images/attributes/weapon/shiv.jpeg',
    imageGenPrompt: 'A crudely sharpened piece of rusty metal with a cloth-wrapped handle.',
    forgeAttributes: { '5': 'power_t8', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'bloodmoon_leather_straps': { id: 'bloodmoon_leather_straps', name: 'Leather Straps', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 7600,
    description: 'It\'s not much, but it\'s better than nothing.',
    icon: ' L ',
    image: 'images/attributes/armor/leatherStraps.jpeg',
    imageGenPrompt: 'A set of worn leather straps and plates worn as makeshift armor.',
    forgeAttributes: { '5': 'power_t8', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'bloodmoon_demon_eye': { id: 'bloodmoon_demon_eye', name: 'Demon Eye', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 7750,
    description: 'An eye from a fallen demon. It still watches.',
    icon: ' D ',
    image: 'images/attributes/ring/demonEye.jpeg',
    imageGenPrompt: 'A reptilian eye with a fiery pupil, set into a ring.',
    forgeAttributes: { '5': 'power_t8', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'bloodmoon_soul_cage': { id: 'bloodmoon_soul_cage', name: 'Soul Cage', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 8000,
    description: 'A small, ornate cage containing a faintly glowing wisp.',
    icon: ' S ',
    image: 'images/attributes/misc/soulCage.jpeg',
    imageGenPrompt: 'A small, ornate birdcage containing a captured, glowing soul.',
    forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
  'bloodmoon_eternal_flame': { id: 'bloodmoon_eternal_flame', name: 'Eternal Flame', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 8100,
    description: 'A flame that never dies, fueled by rage.',
    icon: '🔥',
    image: 'images/attributes/amulet/eternalFlame.jpeg',
    imageGenPrompt: 'A magical, eternally burning flame contained within a glass amulet.',
    forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
};
