import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const interdimensionalBreakItems: { [key: string]: Item } = {
  'interdimensional_reality_blade': { id: 'interdimensional_reality_blade', name: 'Reality Blade', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 12000, description: 'Cuts through space and time.', icon: '✨', forgeAttributes: { '5': 'power_t8', '10': 'xp_t3', '15': 'perm_perk_weapon' } },
  'interdimensional_paradox_plate': { id: 'interdimensional_paradox_plate', name: 'Paradox Plate', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 11500, description: 'This armor has not been invented yet.', icon: '🌀', forgeAttributes: { '5': 'power_t8', '10': 'gold_t3', '15': 'perm_perk_armor' } },
  'interdimensional_broken_hourglass': { id: 'interdimensional_broken_hourglass', name: 'Broken Hourglass', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 10000, description: 'Time is on your side. And that side. And all sides.', icon: '⌛', forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
  'interdimensional_glitch_fragment': { id: 'interdimensional_glitch_fragment', name: 'Glitch Fragment', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 9800,
    description: 'A weapon that flickers in and out of existence.',
    icon: ' G ',
    image: 'images/attributes/weapon/glitchFragment.jpeg',
    imageGenPrompt: 'A dagger that appears to be glitching like a computer error.',
    forgeAttributes: { '5': 'power_t8', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'interdimensional_shifting_cloak': { id: 'interdimensional_shifting_cloak', name: 'Shifting Cloak', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 9700,
    description: 'A cloak that constantly changes color and texture.',
    icon: ' S ',
    image: 'images/attributes/armor/shiftingCloak.jpeg',
    imageGenPrompt: 'A cloak that seems to be made of shifting, glitching patterns.',
    forgeAttributes: { '5': 'power_t8', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'interdimensional_fractal_ring': { id: 'interdimensional_fractal_ring', name: 'Fractal Ring', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 9900,
    description: 'Stare into it for too long and you might see the end of everything.',
    icon: ' F ',
    image: 'images/attributes/ring/fractalRing.jpeg',
    imageGenPrompt: 'A ring with an endlessly receding fractal pattern.',
    forgeAttributes: { '5': 'power_t8', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'interdimensional_causality_knot': { id: 'interdimensional_causality_knot', name: 'Causality Knot', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 10500,
    description: 'A knot that cannot be untied by conventional means.',
    icon: ' K ',
    image: 'images/attributes/misc/causalityKnot.jpeg',
    imageGenPrompt: 'A rope tied into an impossible, four-dimensional knot.',
    forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
  'interdimensional_echo_of_the_future': { id: 'interdimensional_echo_of_the_future', name: 'Echo of the Future', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 11000,
    description: 'A ring that whispers warnings about what is to come.',
    icon: ' E ',
    image: 'images/attributes/ring/echoOfTheFuture.jpeg',
    imageGenPrompt: 'A ring that shows faint, ghostly images of future events.',
    forgeAttributes: { '5': 'power_t8', '10': 'loot_t3', '15': 'perm_perk_ring' } },
};
