import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const heavenItems: { [key: string]: Item } = {
  'heaven_firewall_sword': { id: 'heaven_firewall_sword', name: 'Firewall Sword', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 20000, description: 'Deletes threats from existence.', icon: '🔥', forgeAttributes: { '5': 'power_t9', '10': 'xp_t3', '15': 'perm_perk_weapon' } },
  'heaven_holy_server_rack': { id: 'heaven_holy_server_rack', name: 'Holy Server Rack', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 19000, description: 'Offers divine protection and 99.9% uptime.', icon: '😇', forgeAttributes: { '5': 'power_t9', '10': 'gold_t3', '15': 'perm_perk_armor' } },
  'heaven_admin_access_key': { id: 'heaven_admin_access_key', name: 'Admin Access Key', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 17000, description: 'Grants root access to the simulation.', icon: '🔑', forgeAttributes: { '5': 'gold_t3', '10': 'loot_t3', '15': 'perm_perk_misc' } },
  'heaven_data_stream': { id: 'heaven_data_stream', name: 'Data Stream', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 16500,
    description: 'A whip made of pure, flowing data.',
    icon: ' D ',
    image: 'images/attributes/weapon/dataStream.jpeg',
    imageGenPrompt: 'A whip made of flowing, glowing binary code.',
    forgeAttributes: { '5': 'power_t9', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'heaven_hard_light_armor': { id: 'heaven_hard_light_armor', name: 'Hard-Light Armor', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 16000,
    description: 'Armor constructed from photons. Surprisingly durable.',
    icon: ' H ',
    image: 'images/attributes/armor/hardlightArmor.jpeg',
    imageGenPrompt: 'Armor made of solid, glowing white light.',
    forgeAttributes: { '5': 'power_t9', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'heaven_ring_of_code': { id: 'heaven_ring_of_code', name: 'Ring of Code', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 16800,
    description: 'A ring that allows you to see the source code of reality.',
    icon: ' C ',
    image: 'images/attributes/ring/ringOfCode.jpeg',
    imageGenPrompt: 'A ring that has glowing green computer code scrolling across its surface.',
    forgeAttributes: { '5': 'power_t9', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'heaven_source_code_tablet': { id: 'heaven_source_code_tablet', name: 'Source Code Tablet', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 18000,
    description: 'The user manual for the universe.',
    icon: ' S ',
    image: 'images/attributes/misc/sourceCodeTablet.jpeg',
    imageGenPrompt: 'A glowing tablet displaying the source code of the universe.',
    forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
  'heaven_genesis_seed': { id: 'heaven_genesis_seed', name: 'Genesis Seed', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 18500,
    description: 'The seed from which a new reality can be grown.',
    icon: '🌱',
    image: 'images/attributes/amulet/genesisSeed.jpeg',
    imageGenPrompt: 'A small, glowing seed that contains a swirling galaxy within it.',
    forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
};
