import type { Item } from '../../../types';
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from '../../../types';

export const zooItems: { [key: string]: Item } = {
  'zoo_tranquilizer_rifle': { id: 'zoo_tranquilizer_rifle', name: 'Tranquilizer Rifle', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 30000, description: 'Time for a nap.', icon: '🔫', forgeAttributes: { '5': 'power_t9', '10': 'xp_t3', '15': 'perm_perk_weapon' } },
  'zoo_reinforced_keepers_vest': { id: 'zoo_reinforced_keepers_vest', name: 'Reinforced Keeper\'s Vest', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 28000, description: 'Protects against bites, claws, and existential rage.', icon: ' V ', forgeAttributes: { '5': 'power_t9', '10': 'gold_t3', '15': 'perm_perk_armor' } },
  'zoo_primal_totem': { id: 'zoo_primal_totem', name: 'Primal Totem', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 25000, description: 'Channels the spirit of the beast within.', icon: '🐾', forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
  'zoo_feeding_bucket': { id: 'zoo_feeding_bucket', name: 'Feeding Bucket', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Weapon, power: 24000,
    description: 'A heavy metal bucket. It\'s more effective than you\'d think.',
    icon: ' B ',
    image: 'images/attributes/weapon/feedingBucket.jpeg',
    imageGenPrompt: 'A large, heavy, metal feeding bucket used as a weapon.',
    forgeAttributes: { '5': 'power_t9', '10': 'xp_t1', '15': 'perm_perk_weapon' } },
  'zoo_khaki_shorts': { id: 'zoo_khaki_shorts', name: 'Khaki Shorts', rarity: ItemRarity.Common, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Armor, power: 23500,
    description: 'Comfortable and practical for observing dangerous creatures.',
    icon: ' K ',
    image: 'images/attributes/armor/khakiShorts.jpeg',
    imageGenPrompt: 'A pair of sensible khaki shorts.',
    forgeAttributes: { '5': 'power_t9', '10': 'gold_t1', '15': 'perm_perk_armor' } },
  'zoo_key_to_cages': { id: 'zoo_key_to_cages', name: 'Key to Cages', rarity: ItemRarity.Rare, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Ring, power: 24500,
    description: 'Unlocks every cage in the zoo.',
    icon: '🔑',
    image: 'images/attributes/ring/keyToCages.jpeg',
    imageGenPrompt: 'A single, ornate key on a simple ring.',
    forgeAttributes: { '5': 'power_t9', '10': 'loot_t1', '15': 'perm_perk_ring' } },
  'zoo_exotic_animal_pelt': { id: 'zoo_exotic_animal_pelt', name: 'Exotic Animal Pelt', rarity: ItemRarity.Epic, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Misc, power: 26000,
    description: 'A trophy from a creature that no longer exists.',
    icon: ' E ',
    image: 'images/attributes/misc/exoticAnimalPelt.jpeg',
    imageGenPrompt: 'The pelt of a strange, exotic, and possibly mythical animal.',
    forgeAttributes: { '5': 'gold_t2', '10': 'loot_t2', '15': 'perm_perk_misc' } },
  'zoo_alpha_fang': { id: 'zoo_alpha_fang', name: 'Alpha Fang', rarity: ItemRarity.Legendary, type: ItemType.Equipable, category: ItemCategory.Standard, slot: EquipmentSlot.Amulet, power: 27000,
    description: 'The tooth of the pack leader. It radiates dominance.',
    icon: ' F ',
    image: 'images/attributes/amulet/alphaFang.jpeg',
    imageGenPrompt: 'A large, sharp fang from a predator, worn as a pendant.',
    forgeAttributes: { '5': 'gold_t3', '10': 'xp_t3', '15': 'perm_perk_amulet' } },
};
