
import type { Badge } from '../../types';

export const miscellaneousBadges: { [key: string]: Badge } = {
    misc_not_a_bitch: { id: 'misc_not_a_bitch', name: 'Not a Bitch', description: 'Fight a boss with less than a 5% chance of winning.', icon: '🎲', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_POWER', value: 1.001 }, bonusDescription: '+0.1% Global Power' },
    misc_leeroy_jenkins: { id: 'misc_leeroy_jenkins', name: 'Leeroy Jenkins', description: 'Start and cancel 10 missions in a row.', icon: '🏃‍♂️', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_LOOT_CHANCE', value: 1.001 }, bonusDescription: '+0.1% Global Loot Chance' },
    misc_frugal_fighter: { id: 'misc_frugal_fighter', name: 'Frugal Fighter', description: 'Defeat a boss while wearing only Common quality items.', icon: '🧑‍🌾', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_GOLD', value: 1.005 }, bonusDescription: '+0.5% Global Gold' },
    misc_what_does_this_do: { id: 'misc_what_does_this_do', name: 'What Does This Button Do?', description: 'Equip "The Big Red Button".', icon: '🔴', category: 'Miscellaneous', bonus: { type: 'ADD_PERMANENT_POWER', value: 1 }, bonusDescription: '+1 Permanent Power' },
    misc_hoarder: { id: 'misc_hoarder', name: 'Hoarder', description: 'Have over 1,000 of a single stackable item in your inventory.', icon: '📦', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_LOOT_CHANCE', value: 1.005 }, bonusDescription: '+0.5% Global Loot Chance' },
    misc_pacifist: { id: 'misc_pacifist', name: 'Pacifist', description: 'Reach Level 10 without ever equipping a weapon.', icon: '🕊️', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_XP', value: 1.01 }, bonusDescription: '+1% Global XP' },
    misc_the_collector: { id: 'misc_the_collector', name: 'The Collector', description: 'Own at least one of every type of Reptilian Part at the same time.', icon: '🧬', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_LOOT_CHANCE', value: 1.01 }, bonusDescription: '+1% Global Loot Chance' },
    misc_bad_luck_brian: { id: 'misc_bad_luck_brian', name: 'Bad Luck Brian', description: 'Fail 5 forge attempts in a row at 90%+ success chance.', icon: '😭', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_LOOT_CHANCE', value: 1.01 }, bonusDescription: '+1% Global Loot Chance' },
    misc_dietician: { id: 'misc_dietician', name: 'Dietician', description: 'Feed a single Homunculus one of every type of food.', icon: '🍎', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_XP', value: 1.005 }, bonusDescription: '+0.5% Global XP' },
    misc_nudist_colony: { id: 'misc_nudist_colony', name: 'Nudist Colony', description: 'Have 5 adult homunculi with no gear equipped at the same time.', icon: '🍑', category: 'Miscellaneous', bonus: { type: 'ADD_PERMANENT_POWER', value: 10 }, bonusDescription: '+10 Permanent Power' },
    misc_the_gambler: { id: 'misc_the_gambler', name: 'The Gambler', description: 'Get only Common items from 10 caches in a row.', icon: '🎰', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_LOOT_CHANCE', value: 1.01 }, bonusDescription: '+1% Global Loot Chance' },
    misc_stonks: { id: 'misc_stonks', name: 'Stonks', description: 'Collect over $10,000 from a single homunculus payday.', icon: '📈', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_GOLD', value: 1.01 }, bonusDescription: '+1% Global Gold' },
    misc_forgot_to_clock_out: { id: 'misc_forgot_to_clock_out', name: 'Forgot To Clock Out', description: 'Let a single homunculus work for over 7 real-life days.', icon: '😴', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_GOLD', value: 1.01 }, bonusDescription: '+1% Global Gold' },
    misc_one_trick_pony: { id: 'misc_one_trick_pony', name: 'One Trick Pony', description: 'Max a homunculus trait before any other trait is above level 1.', icon: '🎯', category: 'Miscellaneous', bonus: { type: 'MULTIPLY_POWER', value: 1.005 }, bonusDescription: '+0.5% Global Power' },
};
