

export const PREDEFINED_MESSAGES: Record<string, string[]> = {
  "Greetings": [
    "Hello everyone!",
    "Hi!",
    "Hey, good to see you all.",
    "Good luck, everyone!",
    "Let's have a great game.",
    "Ready to play?",
    "What's up?",
    "Let's win some money!",
    "Shuffle up and deal!",
    "Evening all.",
  ],
  "Gameplay - Positive": [
    "Nice win!",
    "Great hand!",
    "I'm on a roll!",
    "Winner winner chicken dinner!",
    "Blackjack!",
    "Feeling lucky today!",
    "I'm all in!",
    "That was a close one.",
    "Good bet.",
    "Pay the man!",
    "That's how you do it!",
    "I'm feeling it!",
    "Perfect card!",
    "The cards are hot!",
    "Doubled down and won!",
    "Split and won both!",
  ],
  "Gameplay - Negative": [
    "Tough luck.",
    "Ouch, that hurt.",
    "Busted!",
    "The dealer is hot tonight.",
    "Not my day...",
    "Should have stood.",
    "One card away...",
    "Wrong move.",
    "Bad beat.",
    "Should have hit.",
    "The deck is cold.",
    "Can't catch a break.",
    "Dealer always has it.",
    "Why did I split?",
  ],
  "Reactions": [
    "Wow!",
    "LOL",
    "OMG!",
    "Unbelievable!",
    "Haha, nice!",
    "No way!",
    "Impressive!",
    "Ugh...",
    "...",
    "Seriously?",
    "Oof.",
    "Phew!",
    "Incredible!",
    "You're kidding me.",
    "*facepalm*",
    "Nice!",
  ],
  "Strategy Talk": [
    "Always split Aces and 8s.",
    "Never take insurance.",
    "Should I hit this 16?",
    "What's the count?",
    "Basic strategy says to stand.",
    "I'm going by the book here.",
    "Let's play the odds."
  ],
  "Compliments & Encouragement": [
    "Well played.",
    "You've got this!",
    "Nice call.",
    "Good luck on your next hand.",
    "Smart move.",
    "You're a good player."
  ],
  "Taunts & Bluffing (Playful)": [
    "Feeling confident?",
    "I think the dealer is bluffing.",
    "You're not gonna hit that, are you?",
    "I can feel a bust coming.",
    "Pressure's on!",
    "Show me the money!"
  ],
  "Table Talk": [
    "Change the dealer!",
    "New shoe, new luck.",
    "Is this a fresh deck?",
    "Anyone need a drink?",
    "Music is good tonight.",
    "This table is lively!"
  ],
  "General Chat": [
    "How's everyone doing?",
    "Good game!",
    "Anyone on a winning streak?",
    "What's your favorite game here?",
    "First time playing this.",
    "Let's do this!",
    "Drinks on me if I win this hand!",
    "This is my favorite casino game.",
    "Just trying to have some fun.",
  ],
  "Goodbyes": [
    "Gotta go, bye everyone.",
    "See you next time!",
    "It was fun, take care.",
    "Cashing out!",
    "Good luck for the rest of you.",
    "Bye!",
    "That's enough for me.",
    "Time to hit the hay.",
    "Good night everyone.",
    "All done, good luck!",
  ],
};

export const ALL_MESSAGES = Object.values(PREDEFINED_MESSAGES).flat();