import type { Item } from "../../types";
import { ItemRarity, ItemType, EquipmentSlot, ItemCategory } from "../../types";

export const bossItems: { [key: string]: Item } = {
  boss_lunch_ladys_ladle: {
    id: "boss_lunch_ladys_ladle",
    name: "Lunch Lady's Ladle",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 50,
    description:
      "It has served a million meals and a million years of detention. Smells faintly of despair and Salisbury steak.",
    icon: "🥣",
    image: "images/boss-items/ladle.png",
    imageGenPrompt:
      "A large, spectral, glowing metal ladle, dripping with a mysterious green substance.",
    forgeAttributes: {
      "5": "power_t4",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_dumbbell_of_a_thousand_reps: {
    id: "boss_dumbbell_of_a_thousand_reps",
    name: "Dumbbell of 1k Reps",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 60,
    description: "Each rep added a bit of its user's soul. It's very heavy.",
    icon: "🏋️",
    image: "images/boss-items/soulDumbbell.png",
    imageGenPrompt:
      "A massive, black iron dumbbell that radiates a powerful aura of pure energy.",
    forgeAttributes: {
      "5": "power_t4",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_stamp_of_authority: {
    id: "boss_stamp_of_authority",
    name: "Stamp of Authority",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Ring,
    power: 90,
    description: "This stamp can return any argument to sender.",
    icon: "📬",
    image: "images/boss-items/stampOfAuthority.png",
    imageGenPrompt:
      "An ornate, heavy-duty rubber stamp with a glowing, otherworldly sigil on it, worn as a ring.",
    forgeAttributes: {
      "5": "power_t4",
      "10": "loot_t3",
      "15": "perm_perk_ring",
    },
  },
  boss_sash_of_supreme_authority: {
    id: "boss_sash_of_supreme_authority",
    name: "Sash of Supreme Authority",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 150,
    description:
      'Grants the wearer the unquestionable right to ask "Where do you think YOU\'RE going?".',
    icon: "🎗️",
    image: "images/boss-items/hallMonitorSash.png",
    imageGenPrompt:
      "A bright orange hall monitor sash that glows with immense power.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_the_defibrillator: {
    id: "boss_the_defibrillator",
    name: "The Defibrillator",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 250,
    description: "CLEAR! ...a path through your enemies.",
    icon: "⚡",
    image: "images/boss-items/defibrillator.png",
    imageGenPrompt:
      "A pair of defibrillator paddles crackling with powerful lightning.",
    forgeAttributes: {
      "5": "power_t6",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_the_last_hot_dog: {
    id: "boss_the_last_hot_dog",
    name: "The Last Hot Dog",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 320,
    description:
      "A surprisingly powerful, fossilized sausage in a bun. Smells... eternal.",
    icon: "🌭",
    image: "images/boss-items/lastHotDog.png",
    imageGenPrompt:
      "A petrified hot dog in a bun, hanging from a golden chain like a precious amulet.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  boss_the_neuralyzer: {
    id: "boss_the_neuralyzer",
    name: "The Neuralyzer",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 400,
    description: "What were we talking about again?",
    icon: "✨",
    image: "images/boss-items/neuralyzer.png",
    imageGenPrompt:
      "A sleek, silver, pen-like device from Men In Black, emitting a bright flash.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_the_big_red_button: {
    id: "boss_the_big_red_button",
    name: "The Big Red Button",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Ring,
    power: 500,
    description: "Go on. Push it. You know you want to.",
    icon: "🔴",
    image: "images/boss-items/bigRedButton.png",
    imageGenPrompt: "A comically large, tempting red button mounted on a ring.",
    forgeAttributes: {
      "5": "power_t7",
      "10": "loot_t3",
      "15": "perm_perk_ring",
    },
  },
  boss_tinfoil_hat_of_ultimate_protection: {
    id: "boss_tinfoil_hat_of_ultimate_protection",
    name: "Tinfoil Hat",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 650,
    description: "Blocks psychic signals, radio waves, and compliments.",
    icon: "🧠",
    image: "images/boss-items/tinfoilHat.png",
    imageGenPrompt:
      "An expertly crafted, shiny tinfoil hat that hums with protective energy.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_the_priority_tag: {
    id: "boss_the_priority_tag",
    name: "The Priority Tag",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 800,
    description:
      "Ensures your soul arrives at its destination before anyone else's.",
    icon: "🏷️",
    image: "images/boss-items/priorityTag.png",
    imageGenPrompt: 'A glowing red "PRIORITY" luggage tag worn as a necklace.',
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  boss_the_unfastened_seatbelt: {
    id: "boss_the_unfastened_seatbelt",
    name: "Unfastened Seatbelt",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 1000,
    description: "A flail of minor inconvenience and major damage.",
    icon: "🔗",
    image: "images/boss-items/seatbeltFlail.png",
    imageGenPrompt:
      "A car seatbelt with a heavy metal buckle, being swung like a flail.",
    forgeAttributes: {
      "5": "power_t7",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_the_alien_probe: {
    id: "boss_the_alien_probe",
    name: "The Alien Probe",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 1300,
    description: "For... scientific research.",
    icon: "🔬",
    image: "images/boss-items/alienProbe.png",
    imageGenPrompt:
      "A stereotypical alien anal probe device, glowing ominously.",
    forgeAttributes: {
      "5": "power_t7",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_the_perfect_copy: {
    id: "boss_the_perfect_copy",
    name: "The Perfect Copy",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 1600,
    description:
      "An exam paper with all the right answers. It's cheating, but who's gonna know?",
    icon: "📄",
    image: "images/boss-items/perfectCopy.png",
    imageGenPrompt: "A magical glowing exam paper with an A++ grade on it.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_quackmageddons_beak: {
    id: "boss_quackmageddons_beak",
    name: "Quackmageddon's Beak",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 200,
    description:
      "The gilded beak of the Lord of the Pond. It can shatter breadcrumbs and egos with equal ease.",
    icon: "🦆",
    image: "images/boss-items/goldenBeak.png",
    imageGenPrompt: "A powerful, golden duck beak worn as a helmet.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_sentient_mops_bucket: {
    id: "boss_sentient_mops_bucket",
    name: "Sentient Mop's Bucket",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Armor,
    power: 120,
    description:
      "A bucket that has seen too much. It whispers cleaning tips and the secrets of the cosmos.",
    icon: "🪣",
    image: "images/boss-items/mopBucket.png",
    imageGenPrompt:
      "A metal mop bucket worn as a helmet, with a single, knowing eye peering from inside.",
    forgeAttributes: {
      "5": "power_t5",
      "10": "gold_t3",
      "15": "perm_perk_armor",
    },
  },
  boss_presidents_secret: {
    id: "boss_presidents_secret",
    name: "The President's Secret",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 2500,
    description:
      "It's not a document. It's not a key. It's his favorite, surprisingly powerful, novelty tie.",
    icon: "👔",
    image: "images/boss-items/presidentsTie.png",
    imageGenPrompt:
      "A patriotic red, white, and blue tie, tied into a perfect knot and worn as a necklace.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  boss_steves_clipboard: {
    id: "boss_steves_clipboard",
    name: "Steve's Clipboard",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 3200,
    description: "The most powerful weapon of all: bureaucracy.",
    icon: "📋",
    image: "images/boss-items/stevesClipboard.png",
    imageGenPrompt:
      "A powerful, glowing clipboard that radiates an aura of pure authority and paperwork.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  "boss_illudium_q-36": {
    id: "boss_illudium_q-36",
    name: "Illudium Q-36",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 4500,
    description:
      "The Illudium Q-36 Explosive Space Modulator. May not actually modulate space, but it does explode.",
    icon: "💣",
    image: "images/boss-items/spaceModulator.png",
    imageGenPrompt:
      "The Illudium Q-36 Explosive Space Modulator from Looney Tunes.",
    forgeAttributes: {
      "5": "power_t8",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_the_pacifier_of_silence: {
    id: "boss_the_pacifier_of_silence",
    name: "Pacifier of Silence",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 5500,
    description: "Finally, some peace and quiet.",
    icon: "🍼",
    image: "images/boss-items/pacifierOfSilence.png",
    imageGenPrompt:
      "A large, ornate baby pacifier hanging from a chain, glowing with quieting energy.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  "boss_silver-lined_oxygen_tank": {
    id: "boss_silver-lined_oxygen_tank",
    name: "Silver-Lined O2 Tank",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Armor,
    power: 8000,
    description: "Breathe easy, knowing you're safe from lunar lycanthropes.",
    icon: "🌕",
    image: "images/boss-items/silverOxygenTank.png",
    imageGenPrompt:
      "An astronaut's oxygen tank backpack made of shining, polished silver.",
    forgeAttributes: {
      "5": "power_t9",
      "10": "gold_t3",
      "15": "perm_perk_armor",
    },
  },
  boss_the_cosmic_snooze_button: {
    id: "boss_the_cosmic_snooze_button",
    name: "Cosmic Snooze Button",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Ring,
    power: 11000,
    description: "Just five more millennia...",
    icon: "💤",
    image: "images/boss-items/cosmicSnoozeButton.png",
    imageGenPrompt:
      "A ring with a large, glowing button shaped like a crescent moon and stars.",
    forgeAttributes: {
      "5": "power_t9",
      "10": "loot_t3",
      "15": "perm_perk_ring",
    },
  },
  boss_the_royal_plunger: {
    id: "boss_the_royal_plunger",
    name: "The Royal Plunger",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 16000,
    description: "Can unclog any problem.",
    icon: "🪠",
    image: "images/boss-items/royalPlunger.png",
    imageGenPrompt:
      "A golden toilet plunger, topped with a crown, held like a scepter.",
    forgeAttributes: {
      "5": "power_t9",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  "boss_scales_of_work-life_balance": {
    id: "boss_scales_of_work-life_balance",
    name: "Scales of Work-Life",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 24000,
    description: "Perfectly balanced. As nothing should be.",
    icon: "⚖️",
    image: "images/boss-items/scalesOfWorkLife.png",
    imageGenPrompt: "A set of glowing, ethereal balancing scales.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
  boss_the_fragmented_crown: {
    id: "boss_the_fragmented_crown",
    name: "The Fragmented Crown",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 35000,
    description: "A symbol of broken oaths and immense power.",
    icon: "👑",
    image: "images/boss-items/fragmentedCrown.png",
    imageGenPrompt:
      "A shattered royal crown, with the pieces floating together, held by a dark energy.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  "boss_junk-forged_exosuit": {
    id: "boss_junk-forged_exosuit",
    name: "Junk-Forged Exosuit",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Armor,
    power: 48000,
    description: "It's ugly, it's loud, but it works.",
    icon: "🤖",
    image: "images/boss-items/junkExosuit.png",
    imageGenPrompt:
      "A powerful exosuit cobbled together from scrap metal, car parts, and old appliances.",
    forgeAttributes: {
      "5": "power_t9",
      "10": "gold_t3",
      "15": "perm_perk_armor",
    },
  },
  boss_grandfathers_pocketwatch: {
    id: "boss_grandfathers_pocketwatch",
    name: "Grandfather's Watch",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Amulet,
    power: 70000,
    description: "Don't step on it.",
    icon: "⌚",
    image: "images/boss-items/grandfathersWatch.png",
    imageGenPrompt:
      "An antique, ornate pocketwatch that seems to bend time around it.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "xp_t3",
      "15": "perm_perk_amulet",
    },
  },
  boss_the_tranq_gun: {
    id: "boss_the_tranq_gun",
    name: "The Tranq Gun",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Weapon,
    power: 130000,
    description: "Puts even the most ferocious beasts to sleep. Permanently.",
    icon: "🔫",
    image: "images/boss-items/tranqGun.png",
    imageGenPrompt:
      "A high-tech tranquilizer dart gun, looking powerful and dangerous.",
    forgeAttributes: {
      "5": "power_t9",
      "10": "xp_t3",
      "15": "perm_perk_weapon",
    },
  },
  boss_the_elders_skull: {
    id: "boss_the_elders_skull",
    name: "The Elder's Skull",
    rarity: ItemRarity.Legendary,
    type: ItemType.Equipable,
    category: ItemCategory.Boss,
    slot: EquipmentSlot.Misc,
    power: 160000,
    description: "Full of wisdom, and calcium.",
    icon: "💀",
    image: "images/boss-items/eldersSkull.png",
    imageGenPrompt:
      "A giant, ancient, reptilian skull that glows with inner wisdom and power.",
    forgeAttributes: {
      "5": "gold_t3",
      "10": "loot_t3",
      "15": "perm_perk_misc",
    },
  },
};
